# Generated by Django 3.1.4 on 2020-12-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'author')},
        ),
    ]
