# Generated by Django 3.1.4 on 2020-12-02 19:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpublish',
            name='website',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 19, 23, 37, 107389, tzinfo=utc), help_text='By defualt date is now + 7'),
        ),
    ]
