# Generated by Django 3.1.4 on 2020-12-02 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emanagement', '0002_auto_20201203_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 19, 40, 40, 997759, tzinfo=utc), help_text='By defualt date is now + 7'),
        ),
    ]
