# Generated by Django 3.1.4 on 2020-12-02 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('emanagement', '0003_auto_20201203_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[(None, 'Select Language'), ('Action and adventure', 'Action and adventure'), ('Art', 'Art'), ('Alternate history', 'Alternate history'), ('Autobiography', 'Autobiography'), ('Anthology', 'Anthology'), ('Biography', 'Biography'), ('Chick lit', 'Chick lit'), ('Book review', 'Book review'), ("Children's", "Children's"), ('Cookbook', 'Cookbook'), ('Comic book', 'Comic book'), ('Diary', 'Diary'), ('Coming-of-age', 'Coming-of-age'), ('Dictionary', 'Dictionary'), ('Crime', 'Crime'), ('Encyclopedia', 'Encyclopedia'), ('Drama', 'Drama'), ('Guide', 'Guide'), ('Fairytale', 'Fairytale'), ('Health', 'Health'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Graphic novel', 'Graphic novel'), ('Journal', 'Journal'), ('Historical fiction', 'Historical fiction'), ('Math', 'Math'), ('Horror', 'Horror'), ('Memoir', 'Memoir'), ('Mystery Prayer', 'Mystery Prayer'), ('Paranormal romance', 'Paranormal romance'), ('Religion, spirituality and new age', 'Religion, spirituality and new age'), ('Picture book', 'Picture book'), ('Textbook', 'Textbook'), ('Poetry', 'Poetry'), ('Review', 'Review'), ('Political thriller', 'Political thriller'), ('Science', 'Science'), ('Romance', 'Romance'), ('Self help', 'Self help'), ('Satire', 'Satire'), ('Travel', 'Travel'), ('Science fiction', 'Science fiction'), ('True crime', 'True crime'), ('Short story', 'Short story'), ('Suspense', 'Suspense'), ('Thriller', 'Thriller'), ('Young adult', 'Young adult')], editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 19, 43, 2, 829055, tzinfo=utc), help_text='By defualt date is now + 7'),
        ),
    ]
